<?php
/**
 *
 *  Magestore
 *   NOTICE OF LICENSE
 *
 *   This source file is subject to the Magestore.com license that is
 *   available through the world-wide-web at this URL:
 *   http://www.magestore.com/license-agreement.html
 *
 *   DISCLAIMER
 *
 *   Do not edit or add to this file if you wish to upgrade this extension to newer
 *   version in the future.
 *
 * @category    Magestore
 * @package     Magestore_Coresuccess
 * @copyright   Copyright (c) 2016 Magestore (http://www.magestore.com/)
 * @license     http://www.magestore.com/license-agreement.html
 *
 *
 */

/**
 * Class CsvService
 */
class Magestore_Coresuccess_Model_Service_FileProcess_CsvService extends Varien_File_Csv
{
    /**
     * CsvService constructor.
     */
    public function __construct()
    {
        ini_set('auto_detect_line_endings', true);
    }

    public function getData($file)
    {
        return parent::getData($file); // TODO: Change the autogenerated stub
    }
}